### ISSUE TITLE
BufferedImage DefaultRandomGenerator Unknown image type ReflectionException

### ISSUE THREAD

**Issue by panosgit** [oshoukry/openpojo#113]
when a class with 
BufferedImage. 
the DefaultRandomGenerator causes Unknown image type
causing ReflectionException.
Could you please check?

com.openpojo.reflection.exception.ReflectionException
	at com.openpojo.reflection.exception.ReflectionException.getInstance(ReflectionException.java:51)
	at com.openpojo.reflection.impl.PojoMethodImpl.invoke(PojoMethodImpl.java:86)
	at com.openpojo.reflection.construct.InstanceFactory.doGetInstance(InstanceFactory.java:119)
	at com.openpojo.reflection.construct.InstanceFactory.getInstance(InstanceFactory.java:75)
	at com.openpojo.reflection.construct.InstanceFactory.getLeastCompleteInstance(InstanceFactory.java:103)
	at com.openpojo.random.impl.DefaultRandomGenerator.doGenerate(DefaultRandomGenerator.java:63)

Caused by: java.lang.IllegalArgumentException: Unknown image type -881485859
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:501)
	... 48 more

**Comment by oshoukry** [comment]
Fixed in 0.8.10.

**Comment by panosgit** [comment]
Thank you 👍
