### ISSUE TITLE
Generic declared Collection<SomeType> causes intermittent failures.

### ISSUE THREAD

**Issue by oshoukry** [oshoukry/openpojo#57]
We get the following non deterministic producable random exception and similar on a build machine:

java.lang.ClassCastException: java.util.HashSet cannot be cast to java.util.List
	at com.openpojo.random.collection.list.ListConcreteRandomGenerator.doGenerate(ListConcreteRandomGenerator.java:72)
	at com.openpojo.random.service.impl.RandomGeneratorAdapter.doGenerate(RandomGeneratorAdapter.java:58)
	at com.openpojo.random.RandomFactory.getRandomValue(RandomFactory.java:110)
	at com.openpojo.validation.test.impl.SetterTester.run(SetterTester.java:42)
	at com.openpojo.validation.PojoValidator.runValidation(PojoValidator.java:82)
...

The tried versions are openpojo 0.6.3, 0.6.5.
With openpojo 0.5.0 the exception seems not to occur.

**Comment by oshoukry** [comment]
This issue was reported @https://code.google.com/p/openpojo/issues/detail?id=56

**Comment by oshoukry** [comment]
A fix has been checked in and will be part of next release.
