### ISSUE TITLE
IncompatibleClassChangeError on Getter/SetterTester() on POJO with ZonedDateTime member

### ISSUE THREAD

**Issue by ssherwood** [oshoukry/openpojo#82]
I have a Pojo that contains a member variable of the Java 8 Date type "ZonedDateTime".

When running an OpenPojo test case on this class, I get an exception:

```
com.openpojo.reflection.exception.ReflectionException: Failed to create instance for class [com.openpojo.reflection.impl.PojoClassImpl [clazz=class java.time.ZonedDateTime, pojoFields=[PojoFieldImpl [field=private static final long java.time.ZonedDateTime.serialVersionUID, fieldGetter=null, fieldSetter=null], PojoFieldImpl [field=private final java.time.LocalDateTime java.time.ZonedDateTime.dateTime, fieldGetter=null, fieldSetter=null], PojoFieldImpl [field=private final java.time.ZoneOffset java.time.ZonedDateTime.offset, fieldGetter=PojoMethodImpl [method=getOffset args=[] return=class java.time.ZoneOffset], fieldSetter=null], PojoFieldImpl [field=private final java.time.ZoneId java.time.ZonedDateTime.zone, fieldGetter=PojoMethodImpl [method=getZone args=[] return=class java.time.ZoneId], fieldSetter=null]], pojoMethods=[PojoMethodImpl [constructor=java.time.ZonedDateTime args=[class java.time.LocalDateTime, class java.time.ZoneOffset, class java.time.ZoneId] return=class java.time.ZonedDateTime], PojoMethodImpl [method=get args=[interface java.time.temporal.TemporalField] return=int], PojoMethodImpl [method=equals args=[class java.lang.Object] return=boolean], PojoMethodImpl [method=toString args=[] return=class java.lang.String], PojoMethodImpl [method=hashCode args=[] return=int], PojoMethodImpl [method=getLong args=[interface java.time.temporal.TemporalField] return=long], PojoMethodImpl [method=format args=[class java.time.format.DateTimeFormatter] return=class java.lang.String], PojoMethodImpl [method=readObject args=[class java.io.ObjectInputStream] return=void], PojoMethodImpl [method=create args=[long, int, class java.time.ZoneId] return=class java.time.ZonedDateTime], PojoMethodImpl [method=query args=[interface java.time.temporal.TemporalQuery] return=class java.lang.Object], PojoMethodImpl [method=of args=[class java.time.LocalDate, class java.time.LocalTime, class java.time.ZoneId] return=class java.time.ZonedDateTime], PojoMethodImpl [method=of args=[int, int, int, int, int, int, int, class java.time.ZoneId] return=class java.time.ZonedDateTime], PojoMethodImpl [method=of args=[class java.time.LocalDateTime, class java.time.ZoneId] return=class java.time.ZonedDateTime], PojoMethodImpl [method=getOffset args=[] return=class java.time.ZoneOffset], PojoMethodImpl [method=writeReplace args=[] return=class java.lang.Object], PojoMethodImpl [method=isSupported args=[interface java.time.temporal.TemporalField] return=boolean], PojoMethodImpl [method=isSupported args=[interface java.time.temporal.TemporalUnit] return=boolean], PojoMethodImpl [method=parse args=[interface java.lang.CharSequence, class java.time.format.DateTimeFormatter] return=class java.time.ZonedDateTime], PojoMethodImpl [method=parse args=[interface java.lang.CharSequence] return=class java.time.ZonedDateTime], PojoMethodImpl [method=range args=[interface java.time.temporal.TemporalField] return=class java.time.temporal.ValueRange], PojoMethodImpl [method=with args=[interface java.time.temporal.TemporalField, long] return=interface java.time.temporal.Temporal], PojoMethodImpl [method=with args=[interface java.time.temporal.TemporalAdjuster] return=class java.time.ZonedDateTime], PojoMethodImpl [method=with args=[interface java.time.temporal.TemporalField, long] return=class java.time.ZonedDateTime], PojoMethodImpl [method=with args=[interface java.time.temporal.TemporalAdjuster] return=interface java.time.chrono.ChronoZonedDateTime], PojoMethodImpl [method=with args=[interface java.time.temporal.TemporalAdjuster] return=interface java.time.temporal.Temporal], PojoMethodImpl [method=with args=[interface java.time.temporal.TemporalField, long] return=interface java.time.chrono.ChronoZonedDateTime], PojoMethodImpl [method=now args=[class java.time.Clock] return=class java.time.ZonedDateTime], PojoMethodImpl [method=now args=[class java.time.ZoneId] return=class java.time.ZonedDateTime], PojoMethodImpl [method=now args=[] return=class java.time.ZonedDateTime], PojoMethodImpl [method=plusSeconds args=[long] return=class java.time.ZonedDateTime], PojoMethodImpl [method=toLocalTime args=[] return=class java.time.LocalTime], PojoMethodImpl [method=ofInstant args=[class java.time.Instant, class java.time.ZoneId] return=class java.time.ZonedDateTime], PojoMethodImpl [method=ofInstant args=[class java.time.LocalDateTime, class java.time.ZoneOffset, class java.time.ZoneId] return=class java.time.ZonedDateTime], PojoMethodImpl [method=plus args=[long, interface java.time.temporal.TemporalUnit] return=class java.time.ZonedDateTime], PojoMethodImpl [method=plus args=[interface java.time.temporal.TemporalAmount] return=class java.time.ZonedDateTime], PojoMethodImpl [method=plus args=[long, interface java.time.temporal.TemporalUnit] return=interface java.time.chrono.ChronoZonedDateTime], PojoMethodImpl [method=plus args=[interface java.time.temporal.TemporalAmount] return=interface java.time.chrono.ChronoZonedDateTime], PojoMethodImpl [method=plus args=[long, interface java.time.temporal.TemporalUnit] return=interface java.time.temporal.Temporal], PojoMethodImpl [method=plus args=[interface java.time.temporal.TemporalAmount] return=interface java.time.temporal.Temporal], PojoMethodImpl [method=toLocalDateTime args=[] return=class java.time.LocalDateTime], PojoMethodImpl [method=toLocalDateTime args=[] return=interface java.time.chrono.ChronoLocalDateTime], PojoMethodImpl [method=getMonthValue args=[] return=int], PojoMethodImpl [method=getHour args=[] return=int], PojoMethodImpl [method=getMinute args=[] return=int], PojoMethodImpl [method=getSecond args=[] return=int], PojoMethodImpl [method=getNano args=[] return=int], PojoMethodImpl [method=from args=[interface java.time.temporal.TemporalAccessor] return=class java.time.ZonedDateTime], PojoMethodImpl [method=writeExternal args=[interface java.io.DataOutput] return=void], PojoMethodImpl [method=readExternal args=[interface java.io.ObjectInput] return=class java.time.ZonedDateTime], PojoMethodImpl [method=getYear args=[] return=int], PojoMethodImpl [method=getMonth args=[] return=class java.time.Month], PojoMethodImpl [method=getDayOfMonth args=[] return=int], PojoMethodImpl [method=getDayOfWeek args=[] return=class java.time.DayOfWeek], PojoMethodImpl [method=getZone args=[] return=class java.time.ZoneId], PojoMethodImpl [method=getDayOfYear args=[] return=int], PojoMethodImpl [method=toLocalDate args=[] return=interface java.time.chrono.ChronoLocalDate], PojoMethodImpl [method=toLocalDate args=[] return=class java.time.LocalDate], PojoMethodImpl [method=withYear args=[int] return=class java.time.ZonedDateTime], PojoMethodImpl [method=withMonth args=[int] return=class java.time.ZonedDateTime], PojoMethodImpl [method=withDayOfMonth args=[int] return=class java.time.ZonedDateTime], PojoMethodImpl [method=withDayOfYear args=[int] return=class java.time.ZonedDateTime], PojoMethodImpl [method=withHour args=[int] return=class java.time.ZonedDateTime], PojoMethodImpl [method=withMinute args=[int] return=class java.time.ZonedDateTime], PojoMethodImpl [method=withSecond args=[int] return=class java.time.ZonedDateTime], PojoMethodImpl [method=withNano args=[int] return=class java.time.ZonedDateTime], PojoMethodImpl [method=truncatedTo args=[interface java.time.temporal.TemporalUnit] return=class java.time.ZonedDateTime], PojoMethodImpl [method=plusYears args=[long] return=class java.time.ZonedDateTime], PojoMethodImpl [method=plusMonths args=[long] return=class java.time.ZonedDateTime], PojoMethodImpl [method=plusWeeks args=[long] return=class java.time.ZonedDateTime], PojoMethodImpl [method=plusDays args=[long] return=class java.time.ZonedDateTime], PojoMethodImpl [method=plusHours args=[long] return=class java.time.ZonedDateTime], PojoMethodImpl [method=plusMinutes args=[long] return=class java.time.ZonedDateTime], PojoMethodImpl [method=plusNanos args=[long] return=class java.time.ZonedDateTime], PojoMethodImpl [method=minus args=[interface java.time.temporal.TemporalAmount] return=interface java.time.temporal.Temporal], PojoMethodImpl [method=minus args=[long, interface java.time.temporal.TemporalUnit] return=class java.time.ZonedDateTime], PojoMethodImpl [method=minus args=[long, interface java.time.temporal.TemporalUnit] return=interface java.time.chrono.ChronoZonedDateTime], PojoMethodImpl [method=minus args=[long, interface java.time.temporal.TemporalUnit] return=interface java.time.temporal.Temporal], PojoMethodImpl [method=minus args=[interface java.time.temporal.TemporalAmount] return=interface java.time.chrono.ChronoZonedDateTime], PojoMethodImpl [method=minus args=[interface java.time.temporal.TemporalAmount] return=class java.time.ZonedDateTime], PojoMethodImpl [method=minusYears args=[long] return=class java.time.ZonedDateTime], PojoMethodImpl [method=minusMonths args=[long] return=class java.time.ZonedDateTime], PojoMethodImpl [method=minusWeeks args=[long] return=class java.time.ZonedDateTime], PojoMethodImpl [method=minusDays args=[long] return=class java.time.ZonedDateTime], PojoMethodImpl [method=minusHours args=[long] return=class java.time.ZonedDateTime], PojoMethodImpl [method=minusMinutes args=[long] return=class java.time.ZonedDateTime], PojoMethodImpl [method=minusSeconds args=[long] return=class java.time.ZonedDateTime], PojoMethodImpl [method=minusNanos args=[long] return=class java.time.ZonedDateTime], PojoMethodImpl [method=until args=[interface java.time.temporal.Temporal, interface java.time.temporal.TemporalUnit] return=long], PojoMethodImpl [method=ofLocal args=[class java.time.LocalDateTime, class java.time.ZoneId, class java.time.ZoneOffset] return=class java.time.ZonedDateTime], PojoMethodImpl [method=ofStrict args=[class java.time.LocalDateTime, class java.time.ZoneOffset, class java.time.ZoneId] return=class java.time.ZonedDateTime], PojoMethodImpl [method=ofLenient args=[class java.time.LocalDateTime, class java.time.ZoneOffset, class java.time.ZoneId] return=class java.time.ZonedDateTime], PojoMethodImpl [method=resolveLocal args=[class java.time.LocalDateTime] return=class java.time.ZonedDateTime], PojoMethodImpl [method=resolveInstant args=[class java.time.LocalDateTime] return=class java.time.ZonedDateTime], PojoMethodImpl [method=resolveOffset args=[class java.time.ZoneOffset] return=class java.time.ZonedDateTime], PojoMethodImpl [method=withEarlierOffsetAtOverlap args=[] return=interface java.time.chrono.ChronoZonedDateTime], PojoMethodImpl [method=withEarlierOffsetAtOverlap args=[] return=class java.time.ZonedDateTime], PojoMethodImpl [method=withLaterOffsetAtOverlap args=[] return=interface java.time.chrono.ChronoZonedDateTime], PojoMethodImpl [method=withLaterOffsetAtOverlap args=[] return=class java.time.ZonedDateTime], PojoMethodImpl [method=withZoneSameLocal args=[class java.time.ZoneId] return=interface java.time.chrono.ChronoZonedDateTime], PojoMethodImpl [method=withZoneSameLocal args=[class java.time.ZoneId] return=class java.time.ZonedDateTime], PojoMethodImpl [method=withZoneSameInstant args=[class java.time.ZoneId] return=class java.time.ZonedDateTime], PojoMethodImpl [method=withZoneSameInstant args=[class java.time.ZoneId] return=interface java.time.chrono.ChronoZonedDateTime], PojoMethodImpl [method=withFixedOffsetZone args=[] return=class java.time.ZonedDateTime], PojoMethodImpl [method=toOffsetDateTime args=[] return=class java.time.OffsetDateTime]]]] using constructor [PojoMethodImpl [constructor=java.time.ZonedDateTime args=[class java.time.LocalDateTime, class java.time.ZoneOffset, class java.time.ZoneId] return=class java.time.ZonedDateTime]]

	at com.openpojo.reflection.exception.ReflectionException.getInstance(ReflectionException.java:51)
	at com.openpojo.reflection.construct.InstanceFactory.createInstance(InstanceFactory.java:227)
	at com.openpojo.reflection.construct.InstanceFactory.getLeastCompleteInstance(InstanceFactory.java:165)
	at com.openpojo.random.impl.DefaultRandomGenerator.doGenerate(DefaultRandomGenerator.java:63)
	at com.openpojo.random.RandomFactory.getRandomValue(RandomFactory.java:99)
	at com.openpojo.random.RandomFactory.getRandomValue(RandomFactory.java:107)
	at com.openpojo.validation.test.impl.GetterTester.run(GetterTester.java:44)
	at com.openpojo.validation.utils.ValidationHelper.runValidation(ValidationHelper.java:101)
	at com.openpojo.validation.impl.DefaultValidator.validate(DefaultValidator.java:46)
	at com.PojoTest.validate(PojoTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: com.openpojo.reflection.exception.ReflectionException: Failed to create instance for class [com.openpojo.reflection.impl.PojoClassImpl [clazz=class java.time.ZoneId, pojoFields=[PojoFieldImpl [field=public static final java.util.Map java.time.ZoneId.SHORT_IDS, fieldGetter=null, fieldSetter=null], PojoFieldImpl [field=private static final long java.time.ZoneId.serialVersionUID, fieldGetter=null, fieldSetter=null]], pojoMethods=[PojoMethodImpl [constructor=java.time.ZoneId args=[] return=class java.time.ZoneId], PojoMethodImpl [method=equals args=[class java.lang.Object] return=boolean], PojoMethodImpl [method=toString args=[] return=class java.lang.String], PojoMethodImpl [method=hashCode args=[] return=int], PojoMethodImpl [method=write args=[interface java.io.DataOutput] return=void], PojoMethodImpl [method=readObject args=[class java.io.ObjectInputStream] return=void], PojoMethodImpl [method=getId args=[] return=class java.lang.String], PojoMethodImpl [method=of args=[class java.lang.String] return=class java.time.ZoneId], PojoMethodImpl [method=of args=[class java.lang.String, interface java.util.Map] return=class java.time.ZoneId], PojoMethodImpl [method=of args=[class java.lang.String, boolean] return=class java.time.ZoneId], PojoMethodImpl [method=writeReplace args=[] return=class java.lang.Object], PojoMethodImpl [method=getDisplayName args=[class java.time.format.TextStyle, class java.util.Locale] return=class java.lang.String], PojoMethodImpl [method=normalized args=[] return=class java.time.ZoneId], PojoMethodImpl [method=systemDefault args=[] return=class java.time.ZoneId], PojoMethodImpl [method=getAvailableZoneIds args=[] return=interface java.util.Set], PojoMethodImpl [method=ofOffset args=[class java.lang.String, class java.time.ZoneOffset] return=class java.time.ZoneId], PojoMethodImpl [method=ofWithPrefix args=[class java.lang.String, int, boolean] return=class java.time.ZoneId], PojoMethodImpl [method=toTemporal args=[] return=interface java.time.temporal.TemporalAccessor], PojoMethodImpl [method=getRules args=[] return=class java.time.zone.ZoneRules], PojoMethodImpl [method=from args=[interface java.time.temporal.TemporalAccessor] return=class java.time.ZoneId]]]] using constructor [PojoMethodImpl [constructor=java.time.ZoneId args=[] return=class java.time.ZoneId]]
	at com.openpojo.reflection.exception.ReflectionException.getInstance(ReflectionException.java:51)
	at com.openpojo.reflection.construct.InstanceFactory.createInstance(InstanceFactory.java:227)
	at com.openpojo.reflection.construct.InstanceFactory.getLeastCompleteInstance(InstanceFactory.java:165)
	at com.openpojo.random.impl.DefaultRandomGenerator.doGenerate(DefaultRandomGenerator.java:63)
	at com.openpojo.random.RandomFactory.getRandomValue(RandomFactory.java:99)
	at com.openpojo.random.RandomFactory.getRandomValue(RandomFactory.java:107)
	at com.openpojo.reflection.construct.InstanceFactory.createInstance(InstanceFactory.java:222)
	... 35 more
Caused by: com.openpojo.reflection.exception.ReflectionException: Failed to create subclass for class: class java.time.ZoneId
	at com.openpojo.reflection.exception.ReflectionException.getInstance(ReflectionException.java:51)
	at com.openpojo.reflection.java.bytecode.asm.ASMService.createSubclassFor(ASMService.java:61)
	at com.openpojo.reflection.java.bytecode.asm.ASMService.createSubclassFor(ASMService.java:46)
	at com.openpojo.reflection.java.bytecode.ByteCodeFactory.getSubClass(ByteCodeFactory.java:54)
	at com.openpojo.reflection.construct.InstanceFactory.wrapAbstractClass(InstanceFactory.java:83)
	at com.openpojo.reflection.construct.InstanceFactory.getInstance(InstanceFactory.java:78)
	at com.openpojo.reflection.construct.InstanceFactory.createInstance(InstanceFactory.java:225)
	... 40 more
Caused by: java.lang.IncompatibleClassChangeError: class com.openpojo.reflection.java.bytecode.asm.SubClassCreator has interface org.objectweb.asm.ClassVisitor as super class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.openpojo.reflection.java.bytecode.asm.ASMService.getSubClassByteCode(ASMService.java:72)
	at com.openpojo.reflection.java.bytecode.asm.ASMService.createSubclassFor(ASMService.java:57)
	... 45 more
```

If I convert the type to the LocalDateTime class, the test case is green.  It seems like the ZoneId object internal to the ZoneDateTime is actually the one causing the problem.

**Comment by oshoukry** [comment]
Thank you very much for reporting this it seems that java 8 re-did quite a bit of the date time, third time is a charm?
I have a failing test, I'll add the wiring to enable random generation of the date/time components for java 8.

**Comment by oshoukry** [comment]
Release 0.8.4 is out, please update and let me know if there are any other issues you are experiencing.
Thank you for your support and interest in OpenPojo.
