### ISSUE TITLE
java.util.TimeZone not handled

### ISSUE THREAD

**Issue by ignaciolarranaga** [oshoukry/openpojo#98]
I'm receiving this exception on a bean with a TimeZone field.

Some suggestion ?

```
com.openpojo.reflection.exception.ReflectionException: Failed to create instance for class [com.openpojo.reflection.impl.PojoClassImpl [clazz=class java.util.TimeZone, pojoFields=[PojoFieldImpl [field=public static final int java.util.TimeZone.SHORT, fieldGetter=null, fieldSetter=null], PojoFieldImpl [field=public static final int java.util.TimeZone.LONG, fieldGetter=null, fieldSetter=null], PojoFieldImpl [field=private static final int java.util.TimeZone.ONE_MINUTE, fieldGetter=null, fieldSetter=null], PojoFieldImpl [field=private static final int java.util.TimeZone.ONE_HOUR, fieldGetter=null, fieldSetter=null], PojoFieldImpl [field=private static final int java.util.TimeZone.ONE_DAY, fieldGetter=null, fieldSetter=null], PojoFieldImpl [field=static final long java.util.TimeZone.serialVersionUID, fieldGetter=null, fieldSetter=null], PojoFieldImpl [field=static final java.util.TimeZone java.util.TimeZone.NO_TIMEZONE, fieldGetter=null, fieldSetter=null], PojoFieldImpl [field=private java.lang.String java.util.TimeZone.ID, fieldGetter=PojoMethodImpl [method=getID args=[] return=class java.lang.String], fieldSetter=PojoMethodImpl [method=setID args=[class java.lang.String] return=void]], PojoFieldImpl [field=private static volatile java.util.TimeZone java.util.TimeZone.defaultTimeZone, fieldGetter=null, fieldSetter=null], PojoFieldImpl [field=static final java.lang.String java.util.TimeZone.GMT_ID, fieldGetter=null, fieldSetter=null], PojoFieldImpl [field=private static final int java.util.TimeZone.GMT_ID_LENGTH, fieldGetter=null, fieldSetter=null], PojoFieldImpl [field=private static volatile java.util.TimeZone java.util.TimeZone.mainAppContextDefault, fieldGetter=null, fieldSetter=null], PojoFieldImpl [field=static final boolean java.util.TimeZone.$assertionsDisabled, fieldGetter=null, fieldSetter=null]], pojoMethods=[PojoMethodImpl [constructor=java.util.TimeZone args=[] return=class java.util.TimeZone], PojoMethodImpl [method=clone args=[] return=class java.lang.Object], PojoMethodImpl [method=getDefault args=[] return=class java.util.TimeZone], PojoMethodImpl [method=getOffset args=[long] return=int], PojoMethodImpl [method=getOffset args=[int, int, int, int, int, int] return=int], PojoMethodImpl [method=setDefault args=[class java.util.TimeZone] return=void], PojoMethodImpl [method=getDisplayName args=[boolean, int, class java.util.Locale] return=class java.lang.String], PojoMethodImpl [method=getDisplayName args=[class java.util.Locale] return=class java.lang.String], PojoMethodImpl [method=getDisplayName args=[] return=class java.lang.String], PojoMethodImpl [method=getDisplayName args=[boolean, int] return=class java.lang.String], PojoMethodImpl [method=getID args=[] return=class java.lang.String], PojoMethodImpl [method=setRawOffset args=[int] return=void], PojoMethodImpl [method=setID args=[class java.lang.String] return=void], PojoMethodImpl [method=getDisplayNames args=[class java.lang.String, class java.util.Locale] return=class [Ljava.lang.String;], PojoMethodImpl [method=getDSTSavings args=[] return=int], PojoMethodImpl [method=useDaylightTime args=[] return=boolean], PojoMethodImpl [method=observesDaylightTime args=[] return=boolean], PojoMethodImpl [method=inDaylightTime args=[class java.util.Date] return=boolean], PojoMethodImpl [method=toZoneId args=[] return=class java.time.ZoneId], PojoMethodImpl [method=getAvailableIDs args=[int] return=class [Ljava.lang.String;], PojoMethodImpl [method=getAvailableIDs args=[] return=class [Ljava.lang.String;], PojoMethodImpl [method=getSystemTimeZoneID args=[class java.lang.String] return=class java.lang.String], PojoMethodImpl [method=getSystemGMTOffsetID args=[] return=class java.lang.String], PojoMethodImpl [method=setDefaultZone args=[] return=class java.util.TimeZone], PojoMethodImpl [method=hasSameRules args=[class java.util.TimeZone] return=boolean], PojoMethodImpl [method=parseCustomTimeZone args=[class java.lang.String] return=class java.util.TimeZone], PojoMethodImpl [method=getTimeZone args=[class java.lang.String] return=class java.util.TimeZone], PojoMethodImpl [method=getTimeZone args=[class java.lang.String, boolean] return=class java.util.TimeZone], PojoMethodImpl [method=getTimeZone args=[class java.time.ZoneId] return=class java.util.TimeZone], PojoMethodImpl [method=getOffsets args=[long, class [I] return=int], PojoMethodImpl [method=getRawOffset args=[] return=int], PojoMethodImpl [method=getDefaultRef args=[] return=class java.util.TimeZone]]]] using constructor [PojoMethodImpl [constructor=java.util.TimeZone args=[] return=class java.util.TimeZone]]
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:662)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.openpojo.reflection.java.bytecode.asm.SimpleClassLoader.loadThisClass(SimpleClassLoader.java:27)
	at com.openpojo.reflection.java.bytecode.asm.ASMService.createSubclassFor(ASMService.java:57)
	at com.openpojo.reflection.java.bytecode.asm.ASMService.createSubclassFor(ASMService.java:46)
	at com.openpojo.reflection.java.bytecode.ByteCodeFactory.getSubClass(ByteCodeFactory.java:53)
	at com.openpojo.reflection.construct.InstanceFactory.wrapAbstractClass(InstanceFactory.java:84)
	at com.openpojo.reflection.construct.InstanceFactory.getInstance(InstanceFactory.java:79)
	at com.openpojo.reflection.construct.InstanceFactory.createInstance(InstanceFactory.java:201)
	at com.openpojo.reflection.construct.InstanceFactory.getLeastCompleteInstance(InstanceFactory.java:141)
	at com.openpojo.random.impl.DefaultRandomGenerator.doGenerate(DefaultRandomGenerator.java:63)
	at com.openpojo.random.RandomFactory.getRandomValue(RandomFactory.java:99)
	at com.openpojo.random.RandomFactory.getRandomValue(RandomFactory.java:107)
	at com.openpojo.validation.test.impl.SetterTester.run(SetterTester.java:43)
	at com.openpojo.validation.utils.ValidationHelper.runValidation(ValidationHelper.java:101)
	at com.openpojo.validation.impl.DefaultValidator.validate(DefaultValidator.java:46)
	at com.hezea.model.POJOTest.validate(POJOTest.java:49)
```

**Comment by oshoukry** [comment]
Thank you for reporting the issue, it has now been fixed and the fix will be in version 0.8.5.
